Repository COSC310-Team-Passio/PassIO-COSC310-EventTicketProject, pull requests merged in 2024-03, with the labels that each got.

#55 Updated checkout, eventEntry and index pages
  PassIO/app.py
  PassIO/static/neon.css
  PassIO/static/neon.css.map
  PassIO/static/neon.scss
  PassIO/static/wireframe.css
  PassIO/static/wireframe.css.map
  PassIO/static/wireframe.scss
  PassIO/templates/checkout.html
  PassIO/templates/eventEntry.html
  PassIO/templates/index.html
  PassIO/templates/search.html
Labels: enhancement

#63 Part 1 of work to date.
  3. Learning Python and how to implement it with a database.pdf
Labels: documentation

#65 Milestone 3 completed
  Milestone #3 Canvas Submission (2).pdf
Labels: documentation

#68 Adding our scrum meeting template
  Scrum Meetings/SCRUM-MEETING-Mar 15.pages
Labels: documentation

#72 Timeline of what Has been focus for the past week
  4. EDU_ (Mar 12-19) .pdf
Labels: documentation

#79 scrum meeting notes Mar 22
  Scrum Meetings/SCRUM-MEETING-Mar 20.pages
Labels: documentation

#80 Login and registration branch
  PassIO/__pycache__/app.cpython-310.pyc
  PassIO/app.py
  PassIO/templates/home.html
  PassIO/templates/loginandregister.html
  PassIO/user.py
Labels: Coding
